package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Biglietto generated by hbm2java
 */
public class Biglietto  implements java.io.Serializable {


     private int idBiglietto;
     private int idCliente;
     private String ora;
     private String titolo;
     private String nomeCinema;
     private String nomeSala;
     private float importo;
     private String numeroPosto;
     private String promo;

    public Biglietto() {
    }

    public Biglietto(int idBiglietto, int idCliente, String ora, String titolo, String nomeCinema, String nomeSala, float importo, String numeroPosto, String promo) {
       this.idBiglietto = idBiglietto;
       this.idCliente = idCliente;
       this.ora = ora;
       this.titolo = titolo;
       this.nomeCinema = nomeCinema;
       this.nomeSala = nomeSala;
       this.importo = importo;
       this.numeroPosto = numeroPosto;
       this.promo = promo;
    }
   
    public int getIdBiglietto() {
        return this.idBiglietto;
    }
    
    public void setIdBiglietto(int idBiglietto) {
        this.idBiglietto = idBiglietto;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getOra() {
        return this.ora;
    }
    
    public void setOra(String ora) {
        this.ora = ora;
    }
    public String getTitolo() {
        return this.titolo;
    }
    
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }
    public String getNomeCinema() {
        return this.nomeCinema;
    }
    
    public void setNomeCinema(String nomeCinema) {
        this.nomeCinema = nomeCinema;
    }
    public String getNomeSala() {
        return this.nomeSala;
    }
    
    public void setNomeSala(String nomeSala) {
        this.nomeSala = nomeSala;
    }
    public float getImporto() {
        return this.importo;
    }
    
    public void setImporto(float importo) {
        this.importo = importo;
    }
    public String getNumeroPosto() {
        return this.numeroPosto;
    }
    
    public void setNumeroPosto(String numeroPosto) {
        this.numeroPosto = numeroPosto;
    }
    public String getPromo() {
        return this.promo;
    }
    
    public void setPromo(String promo) {
        this.promo = promo;
    }




}


