package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nome;
     private String cognome;
     private int punti;
     private String categoria;

    public Cliente() {
    }

    public Cliente(int idCliente, String nome, String cognome, int punti, String categoria) {
       this.idCliente = idCliente;
       this.nome = nome;
       this.cognome = cognome;
       this.punti = punti;
       this.categoria = categoria;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }
    public int getPunti() {
        return this.punti;
    }
    
    public void setPunti(int punti) {
        this.punti = punti;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    @Override
    public String toString() {
        return "Cliente{" + "idCliente=" + idCliente + ", nome=" + nome + ", cognome=" + cognome + ", punti=" + punti + ", categoria=" + categoria + '}';
    }


}


