package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1

import CineMatic.RecensioneFactory;
import cinematic.HibernateUtilities;
import java.util.LinkedList;
import java.util.List;

/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private int idFilm;
     private String titolo;
     private int anno;
     private String trama;
     private String cast;
     private String regista;
     LinkedList<Recensione> listaRecensioni;    
     public HibernateUtilities hibernateUtilities;

    public Film() {
        hibernateUtilities = new HibernateUtilities();
        hibernateUtilities.openSession();   
         listaRecensioni= new  LinkedList<Recensione>();
    }
    

    public Film(int idFilm, String titolo, int anno, String trama, String cast, String regista) {
        
       this.idFilm = idFilm;
       this.titolo = titolo;
       this.anno = anno;
       this.trama = trama;
       this.cast = cast;
       this.regista = regista;     
        hibernateUtilities = new HibernateUtilities();
        hibernateUtilities.openSession();   
         listaRecensioni= new  LinkedList<Recensione>();
    }
   
    public int getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(int idFilm) {
        this.idFilm = idFilm;
    }
    public String getTitolo() {
        return this.titolo;
    }
    
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }
    public int getAnno() {
        return this.anno;
    }
    
    public void setAnno(int anno) {
        this.anno = anno;
    }
    public String getTrama() {
        return this.trama;
    }
    
    public void setTrama(String trama) {
        this.trama = trama;
    }
    public String getCast() {
        return this.cast;
    }
    
    public void setCast(String cast) {
        this.cast = cast;
    }
    public String getRegista() {
        return this.regista;
    }
    
    public void setRegista(String regista) {
        this.regista = regista;
    }
    
    public void caricaListaRecensioni(){
        List<Recensionefilm> lfp = hibernateUtilities.find("recensionefilm","RecensioneFilm");
          
         listaRecensioni = new  LinkedList<Recensione>();
         
         if(lfp !=null)
         {
            for (Recensionefilm rc : lfp) {
                if (rc.getId().getIdFilm()== this.idFilm){            
                    this.listaRecensioni.add(rc);
                }
            }
         }
    }
     
     public void addRecensione(Recensione recensione){
         this.listaRecensioni.add(recensione);
     }
     
    public LinkedList<Recensione> getRecensioni(){
         return listaRecensioni;
     }

    public int getUltimoIdRecensione() {
        if (listaRecensioni.isEmpty()) return 0;
        else {
                Recensionefilm r = (Recensionefilm) listaRecensioni.getLast();
                return r.getId().getIdRecensione();
        }
    }

   public void creaRecensione(int idRecensione, int idCliente, String recensioneTesto, int punteggio) {
           
       RecensioneFactory f = new RecensioneFactory();
           Recensione rc = f.creaRecensione("Film", idRecensione, idCliente, idFilm, recensioneTesto, punteggio);
           addRecensione(rc);
           System.out.println("RECENZIONE :: :E: A:E \n\n\n\n\n "+rc);
           //RecensionefilmId id = new RecensionefilmId(100,100,100);
           //Recensionefilm r = new Recensionefilm(id, "ciao",7);
           hibernateUtilities.save(rc);
            System.out.println("Recensione Film Creata");  
    }

}


