package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Gestorecinema generated by hbm2java
 */
public class Gestorecinema  implements java.io.Serializable {


     private int idGestore;
     private String nome;
     private String cognome;

    public Gestorecinema() {
    }

    public Gestorecinema(int idGestore, String nome, String cognome) {
       this.idGestore = idGestore;
       this.nome = nome;
       this.cognome = cognome;
    }
   
    public int getIdGestore() {
        return this.idGestore;
    }
    
    public void setIdGestore(int idGestore) {
        this.idGestore = idGestore;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }




}


