package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * PoltronaId generated by hbm2java
 */
public class PoltronaId  implements java.io.Serializable {


     private String fila;
     private int posto;
     private int idCinema;
     private int idFilmProiettato;

    public PoltronaId() {
    }

    public PoltronaId(String fila, int posto, int idCinema, int idFilmProiettato) {
       this.fila = fila;
       this.posto = posto;
       this.idCinema = idCinema;
       this.idFilmProiettato = idFilmProiettato;
    }
   
    public String getFila() {
        return this.fila;
    }
    
    public void setFila(String fila) {
        this.fila = fila;
    }
    public int getPosto() {
        return this.posto;
    }
    
    public void setPosto(int posto) {
        this.posto = posto;
    }
    public int getIdCinema() {
        return this.idCinema;
    }
    
    public void setIdCinema(int idCinema) {
        this.idCinema = idCinema;
    }
    public int getIdFilmProiettato() {
        return this.idFilmProiettato;
    }
    
    public void setIdFilmProiettato(int idFilmProiettato) {
        this.idFilmProiettato = idFilmProiettato;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PoltronaId) ) return false;
		 PoltronaId castOther = ( PoltronaId ) other; 
         
		 return ( (this.getFila()==castOther.getFila()) || ( this.getFila()!=null && castOther.getFila()!=null && this.getFila().equals(castOther.getFila()) ) )
 && (this.getPosto()==castOther.getPosto())
 && (this.getIdCinema()==castOther.getIdCinema())
 && (this.getIdFilmProiettato()==castOther.getIdFilmProiettato());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFila() == null ? 0 : this.getFila().hashCode() );
         result = 37 * result + this.getPosto();
         result = 37 * result + this.getIdCinema();
         result = 37 * result + this.getIdFilmProiettato();
         return result;
   }   


}


