package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * PromozioneId generated by hbm2java
 */
public class PromozioneId  implements java.io.Serializable {


     private int idPromozione;
     private int idCinema;

    public PromozioneId() {
    }

    public PromozioneId(int idPromozione, int idCinema) {
       this.idPromozione = idPromozione;
       this.idCinema = idCinema;
    }
   
    public int getIdPromozione() {
        return this.idPromozione;
    }
    
    public void setIdPromozione(int idPromozione) {
        this.idPromozione = idPromozione;
    }
    public int getIdCinema() {
        return this.idCinema;
    }
    
    public void setIdCinema(int idCinema) {
        this.idCinema = idCinema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PromozioneId) ) return false;
		 PromozioneId castOther = ( PromozioneId ) other; 
         
		 return (this.getIdPromozione()==castOther.getIdPromozione())
 && (this.getIdCinema()==castOther.getIdCinema());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPromozione();
         result = 37 * result + this.getIdCinema();
         return result;
   }   


}


