package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Promozione generated by hbm2java
 */
public class Promozione  implements java.io.Serializable {


     private PromozioneId id;

    public Promozione() {
    }

    public Promozione(PromozioneId id) {
       this.id = id;
    }
   
    public PromozioneId getId() {
        return this.id;
    }
    
    public void setId(PromozioneId id) {
        this.id = id;
    }




}


