package db_Online;
// Generated 26-feb-2018 20.49.15 by Hibernate Tools 4.3.1



/**
 * Recensione generated by hbm2java
 */
public abstract class Recensione  implements java.io.Serializable {


         
    public Recensione() {
    }

    public void setIdCliente(int idCliente) {

    }

    public void setIdFilm(int idFilm) {

    }

    public void setContenuto(String recensioneTesto) {

    }

    public void setValutazione(int punteggio) {

    }

    public void setIdRecensione(int idRecensione) {
        
    }
}

