package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Recensionefilm generated by hbm2java
 */
public class Recensionefilm  extends Recensione implements java.io.Serializable {

     private RecensionefilmId id;
     private String contenuto;
     private int valutazione;

    public Recensionefilm() {
    }

    public Recensionefilm(RecensionefilmId id, String contenuto, int valutazione) {
       this.id = id;
       this.contenuto = contenuto;
       this.valutazione = valutazione;
    }
   

    public RecensionefilmId getId() {
        return this.id;
    }
    
    public void setId(RecensionefilmId id) {
        this.id = id;
    }
    public String getContenuto() {
        return this.contenuto;
    }
    
    public void setContenuto(String contenuto) {
        this.contenuto = contenuto;
    }
    public int getValutazione() {
        return this.valutazione;
    }
    
    public void setValutazione(int valutazione) {
        this.valutazione = valutazione;
    }

    public int getIdRecensione() {
        return id.getIdRecensione();
    }




}


