package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * RecensionefilmId generated by hbm2java
 */
public class RecensionefilmId  implements java.io.Serializable {


     private int idRecensione;
     private int idCliente;
     private int idFilm;

    public RecensionefilmId() {
    }

    public RecensionefilmId(int idRecensione, int idCliente, int idFilm) {
       this.idRecensione = idRecensione;
       this.idCliente = idCliente;
       this.idFilm = idFilm;
    }
   
    public int getIdRecensione() {
        return this.idRecensione;
    }
    
    public void setIdRecensione(int idRecensione) {
        this.idRecensione = idRecensione;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdFilm() {
        return this.idFilm;
    }
    
    public void setIdFilm(int idFilm) {
        this.idFilm = idFilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecensionefilmId) ) return false;
		 RecensionefilmId castOther = ( RecensionefilmId ) other; 
         
		 return (this.getIdRecensione()==castOther.getIdRecensione())
 && (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdFilm()==castOther.getIdFilm());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRecensione();
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdFilm();
         return result;
   }   


}


