package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Recensionecinema generated by hbm2java
 */
public class Recensionecinema extends Recensione implements java.io.Serializable {


     private RecensionecinemaId id;
     private String contenuto;
     private int valutazione;

    public Recensionecinema() {
    }

    public Recensionecinema(RecensionecinemaId id, String contenuto, int valutazione) {
       this.id = id;
       this.contenuto = contenuto;
       this.valutazione = valutazione;
    }

    /*public Recensionecinema() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
   
    public RecensionecinemaId getId() {
        return this.id;
    }
    
    public void setId(RecensionecinemaId id) {
        this.id = id;
    }
    public String getContenuto() {
        return this.contenuto;
    }
    
    public void setContenuto(String contenuto) {
        this.contenuto = contenuto;
    }
    public int getValutazione() {
        return this.valutazione;
    }
    
    public void setValutazione(int valutazione) {
        this.valutazione = valutazione;
    }

    public int getIdRecensione() {
        return id.getIdRecensione();
    }


}


