package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * RecensionecinemaId generated by hbm2java
 */
public class RecensionecinemaId  implements java.io.Serializable {


     private int idRecensione;
     private int idCliente;
     private int idCinema;

    public RecensionecinemaId() {
    }

    public RecensionecinemaId(int idRecensione, int idCliente, int idCinema) {
       this.idRecensione = idRecensione;
       this.idCliente = idCliente;
       this.idCinema = idCinema;
    }
   
    public int getIdRecensione() {
        return this.idRecensione;
    }
    
    public void setIdRecensione(int idRecensione) {
        this.idRecensione = idRecensione;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdCinema() {
        return this.idCinema;
    }
    
    public void setIdCinema(int idCinema) {
        this.idCinema = idCinema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecensionecinemaId) ) return false;
		 RecensionecinemaId castOther = ( RecensionecinemaId ) other; 
         
		 return (this.getIdRecensione()==castOther.getIdRecensione())
 && (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdCinema()==castOther.getIdCinema());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRecensione();
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdCinema();
         return result;
   }   


}


