package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1

import cinematic.HibernateUtilities;
import java.util.LinkedList;
import java.util.List;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private SalaId id;
     private String nomeSala;
     private int numeroFile;
     private int numeroPosti;

      public HibernateUtilities hibernateUtilities;
    LinkedList<Poltrona> listaPoltrona;
    
    public Sala() {
        hibernateUtilities = new HibernateUtilities();
        hibernateUtilities.openSession();   
        List<Poltrona> lp = hibernateUtilities.find("poltrona","Poltrona");
        listaPoltrona = new LinkedList<Poltrona>();
    }

    public Sala(SalaId id, String nomeSala, int numeroFile, int numeroPosti) {
       this.id = id;
       this.nomeSala = nomeSala;
       this.numeroFile = numeroFile;
       this.numeroPosti = numeroPosti;
    }
   
    public SalaId getId() {
        return this.id;
    }
    
    public void setId(SalaId id) {
        this.id = id;
    }
    public String getNomeSala() {
        return this.nomeSala;
    }
    
    public void setNomeSala(String nomeSala) {
        this.nomeSala = nomeSala;
    }
    public int getNumeroFile() {
        return this.numeroFile;
    }
    
    public void setNumeroFile(int numeroFile) {
        this.numeroFile = numeroFile;
    }
    public int getNumeroPosti() {
        return this.numeroPosti;
    }
    
    public void setNumeroPosti(int numeroPosti) {
        this.numeroPosti = numeroPosti;
    }

public void caricaListaPoltrona(){
        List<Poltrona> lp = hibernateUtilities.find("poltrona","Poltrona");
        
        System.out.println("Caricamento lista Poltrone...");
        for (Poltrona p : lp) {
            if (p.getIdSala()== this.id.getIdSala()){            
                listaPoltrona.add(p);
                //System.out.println(p);
            }
        }
    }
    
    public LinkedList<Poltrona> getListaPoltrona (){

        return listaPoltrona;
    }
    
    public int getIdSala(String nomeSala){
        return id.getIdSala();
    }

    @Override
    public String toString() {
        return "Sala{" + "id=" + id + ", nomeSala=" + nomeSala + ", numeroFile=" + numeroFile + ", numeroPosti=" + numeroPosti + ", hibernateUtilities=" + hibernateUtilities + ", listaPoltrona=" + listaPoltrona + '}';
    }


}


