package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * SalaId generated by hbm2java
 */
public class SalaId  implements java.io.Serializable {


     private int idSala;
     private int idCinema;

    public SalaId() {
    }

    public SalaId(int idSala, int idCinema) {
       this.idSala = idSala;
       this.idCinema = idCinema;
    }
   
    public int getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(int idSala) {
        this.idSala = idSala;
    }
    public int getIdCinema() {
        return this.idCinema;
    }
    
    public void setIdCinema(int idCinema) {
        this.idCinema = idCinema;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SalaId) ) return false;
		 SalaId castOther = ( SalaId ) other; 
         
		 return (this.getIdSala()==castOther.getIdSala())
 && (this.getIdCinema()==castOther.getIdCinema());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSala();
         result = 37 * result + this.getIdCinema();
         return result;
   }   

    @Override
    public String toString() {
        return "SalaId{" + "idSala=" + idSala + ", idCinema=" + idCinema + '}';
    }


}


