package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Sponsor generated by hbm2java
 */
public class Sponsor  implements java.io.Serializable {


     private int idSponsor;
     private String nome;

    public Sponsor() {
    }

    public Sponsor(int idSponsor, String nome) {
       this.idSponsor = idSponsor;
       this.nome = nome;
    }
   
    public int getIdSponsor() {
        return this.idSponsor;
    }
    
    public void setIdSponsor(int idSponsor) {
        this.idSponsor = idSponsor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


