package db_Online;
// Generated 1-mar-2018 12.26.47 by Hibernate Tools 4.3.1



/**
 * Tipopromozione generated by hbm2java
 */
public class Tipopromozione  implements java.io.Serializable {


     private int idPromozione;
     private String nome;
     private String descrizione;
     private int sconto;
     private int categoria;

    public Tipopromozione() {
    }

    public Tipopromozione(int idPromozione, String nome, String descrizione, int sconto, int categoria) {
       this.idPromozione = idPromozione;
       this.nome = nome;
       this.descrizione = descrizione;
       this.sconto = sconto;
       this.categoria = categoria;
    }
   
    public int getIdPromozione() {
        return this.idPromozione;
    }
    
    public void setIdPromozione(int idPromozione) {
        this.idPromozione = idPromozione;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public int getSconto() {
        return this.sconto;
    }
    
    public void setSconto(int sconto) {
        this.sconto = sconto;
    }
    public int getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(int categoria) {
        this.categoria = categoria;
    }




}


